import { describe, it, expect } from "vitest";
import fc from "fast-check";
import { toStroops, compareAmount, normalizeAmount, isValidAmount } from "../src/domain/money";

// ── Arbitraries ───────────────────────────────────────────────────────────────

/** A valid Stellar amount: 1+ integer digits, optionally `.` + 1–7 fractional digits. */
const validAmount = fc
  .record({
    whole: fc.integer({ min: 0, max: 999_999_999_999 }),
    fracDigits: fc.integer({ min: 0, max: 7 }),
    fracValue: fc.integer({ min: 0, max: 9_999_999 }),
  })
  .map(({ whole, fracDigits, fracValue }) => {
    if (fracDigits === 0) return `${whole}`;
    const maxFrac = 10 ** fracDigits - 1;
    const fv = fracValue % (maxFrac + 1);
    return `${whole}.${fv.toString().padStart(fracDigits, "0")}`;
  });

/**
 * An invalid amount with >7 fractional digits.
 * Generated by appending 8–12 random decimal digits after a whole part.
 */
const tooPreciseAmount = fc
  .tuple(
    fc.integer({ min: 0, max: 999_999_999_999 }),
    fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 8, maxLength: 12 }),
  )
  .map(([whole, digits]) => `${whole}.${digits.join("")}`);

// ── Example-based tests (kept from original) ──────────────────────────────────

describe("money: toStroops", () => {
  it("converts whole numbers", () => {
    expect(toStroops("10")).toBe(100_000_000n);
  });
  it("converts fractional amounts at full precision", () => {
    expect(toStroops("12.3456789")).toBe(123_456_789n);
  });
  it("pads short fractions", () => {
    expect(toStroops("0.5")).toBe(5_000_000n);
  });
  it("rejects floats with >7 decimals", () => {
    expect(() => toStroops("1.123456789")).toThrow();
  });
  it("rejects non-numeric input", () => {
    expect(() => toStroops("abc")).toThrow();
  });
});

describe("money: compareAmount", () => {
  it("detects exact (no float drift)", () => {
    expect(compareAmount("0.1", "0.1")).toBe("exact");
    // the classic 0.1 + 0.2 trap — proven safe via integer stroops
    expect(compareAmount("0.3", "0.3")).toBe("exact");
  });
  it("detects overpayment", () => {
    expect(compareAmount("10.0000001", "10")).toBe("over");
  });
  it("detects underpayment", () => {
    expect(compareAmount("9.9999999", "10")).toBe("under");
  });
});

describe("money: normalizeAmount", () => {
  it("trims trailing zeros", () => {
    expect(normalizeAmount("10.5000000")).toBe("10.5");
    expect(normalizeAmount("10.0000000")).toBe("10");
  });
});

describe("money: isValidAmount", () => {
  it("accepts valid", () => {
    expect(isValidAmount("100")).toBe(true);
    expect(isValidAmount("0.0000001")).toBe(true);
  });
  it("rejects invalid", () => {
    expect(isValidAmount("-1")).toBe(false);
    expect(isValidAmount("1.12345678")).toBe(false);
    expect(isValidAmount("")).toBe(false);
  });
});

// ── Property-based tests ──────────────────────────────────────────────────────
// Run 1 000 cases per property; fast-check prints the seed on failure.

const RUNS = 1_000;

describe("property: money round-trip (parse → format)", () => {
  it("toStroops(normalizeAmount(x)) === toStroops(x)", () => {
    fc.assert(
      fc.property(validAmount, (x) => {
        expect(toStroops(normalizeAmount(x))).toBe(toStroops(x));
      }),
      { numRuns: RUNS },
    );
  });
});

describe("property: money precision", () => {
  it("no valid input with ≤7 decimals loses precision in stroops", () => {
    fc.assert(
      fc.property(validAmount, (x) => {
        const s = toStroops(x);
        // Parse the original string digit‑by‑digit to compute expected stroops
        // independently of toStroops's own code path.
        const dot = x.indexOf(".");
        const wholeDigits = dot >= 0 ? x.slice(0, dot) : x;
        const fracDigits = dot >= 0 ? x.slice(dot + 1) : "";
        const wholeStroops = BigInt(wholeDigits) * 10_000_000n;
        const fracStroops = BigInt((fracDigits + "0000000").slice(0, 7));
        expect(s).toBe(wholeStroops + fracStroops);
      }),
      { numRuns: RUNS },
    );
  });
});

describe("property: money >7 decimals rejected", () => {
  it("isValidAmount returns false for >7 decimals", () => {
    fc.assert(
      fc.property(tooPreciseAmount, (x) => {
        expect(isValidAmount(x)).toBe(false);
      }),
      { numRuns: RUNS },
    );
  });

  it("toStroops throws for >7 decimals", () => {
    fc.assert(
      fc.property(tooPreciseAmount, (x) => {
        expect(() => toStroops(x)).toThrow();
      }),
      { numRuns: RUNS },
    );
  });
});

describe("property: compareAmount is a total order", () => {
  it("is reflexive: compareAmount(a, a) is always exact", () => {
    fc.assert(
      fc.property(validAmount, (a) => {
        expect(compareAmount(a, a)).toBe("exact");
      }),
      { numRuns: RUNS },
    );
  });

  it("is antisymmetric: compareAmount(a,b) and compareAmount(b,a) are complementary", () => {
    fc.assert(
      fc.property(validAmount, validAmount, (a, b) => {
        const ab = compareAmount(a, b);
        const ba = compareAmount(b, a);
        if (ab === "exact") expect(ba).toBe("exact");
        else if (ab === "over") expect(ba).toBe("under");
        else expect(ba).toBe("over");
      }),
      { numRuns: RUNS },
    );
  });

  it("is transitive: if a ≥ b and b ≥ c then a ≥ c", () => {
    fc.assert(
      fc.property(validAmount, validAmount, validAmount, (a, b, c) => {
        const ab = compareAmount(a, b);
        const bc = compareAmount(b, c);
        const ac = compareAmount(a, c);
        // If a ≥ b and b ≥ c then a ≥ c (i.e. ac is not "under")
        const aGeqB = ab === "exact" || ab === "over";
        const bGeqC = bc === "exact" || bc === "over";
        if (aGeqB && bGeqC) {
          expect(ac).not.toBe("under");
        }
        // Also: if a ≤ b and b ≤ c then a ≤ c  (ac is not "over")
        const aLeqB = ab === "exact" || ab === "under";
        const bLeqC = bc === "exact" || bc === "under";
        if (aLeqB && bLeqC) {
          expect(ac).not.toBe("over");
        }
      }),
      { numRuns: RUNS },
    );
  });

  it("is total: compareAmount always returns one of the three values", () => {
    fc.assert(
      fc.property(validAmount, validAmount, (a, b) => {
        const r = compareAmount(a, b);
        expect(["exact", "over", "under"]).toContain(r);
      }),
      { numRuns: RUNS },
    );
  });
});

describe("property: stroops addition is associative", () => {
  it("(toStroops(a) + toStroops(b)) + toStroops(c) === toStroops(a) + (toStroops(b) + toStroops(c))", () => {
    fc.assert(
      fc.property(validAmount, validAmount, validAmount, (a, b, c) => {
        const sa = toStroops(a);
        const sb = toStroops(b);
        const sc = toStroops(c);
        expect((sa + sb) + sc).toBe(sa + (sb + sc));
      }),
      { numRuns: RUNS },
    );
  });
});
