#!/usr/bin/env node
// Uptime + synthetic check for the live demo. Run standalone (`pnpm sweep`) or
// on a schedule (.github/workflows/uptime.yml), which also persists history to
// docs/uptime-state.json and regenerates docs/STATUS.md + the README badges.
//
// No external monitoring service required: this is the whole check.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const statePath = resolve(root, "docs/uptime-state.json");
const statusPath = resolve(root, "docs/STATUS.md");

const API_URL = process.env.UPTIME_API_URL ?? "https://quay-api.onrender.com";
const WEB_URL = process.env.UPTIME_WEB_URL ?? "https://quay-web.vercel.app";
const HISTORY_DAYS = 90;
const FETCH_TIMEOUT_MS = 15000;
const FAILURE_THRESHOLD = 2;

const TARGETS = [
  { id: "api", label: "API", check: () => checkGet(`${API_URL}/health`) },
  { id: "web", label: "Web dashboard", check: () => checkGet(WEB_URL) },
  { id: "synthetic", label: "Create-link (synthetic)", check: () => checkSyntheticLink(API_URL) },
];

async function checkGet(url) {
  const res = await fetchWithTimeout(url, { method: "GET" });
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
}

// Leaves a tiny throwaway link behind on every successful run (title
// "uptime-check", filterable/prunable later) — the point is proving the public
// write path works, not cleanliness. Known trade-off for a demo-scale DB.
async function checkSyntheticLink(apiUrl) {
  const res = await fetchWithTimeout(`${apiUrl}/links`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ title: "uptime-check", amount: "0.0000001", assetCode: "XLM" }),
  });
  if (res.status !== 201) {
    throw new Error(`POST ${apiUrl}/links -> HTTP ${res.status} (expected 201)`);
  }
}

async function fetchWithTimeout(url, opts) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    return await fetch(url, { ...opts, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

async function loadState() {
  try {
    return JSON.parse(await readFile(statePath, "utf8"));
  } catch {
    return { targets: {} };
  }
}

function todayUTC() {
  return new Date().toISOString().slice(0, 10); // "2026-07-27"
}

function emptyTargetState() {
  return { consecutiveFailures: 0, lastStatus: null, lastCheckedAt: null, today: null, history: [] };
}

/** Mutates `state.targets[id]` with this run's result; returns { justFailed, justRecovered }. */
function recordResult(state, id, ok, message) {
  const t = (state.targets[id] ??= emptyTargetState());
  const day = todayUTC();

  if (!t.today || t.today.date !== day) {
    if (t.today) {
      t.history.push({ date: t.today.date, up: t.today.up, down: t.today.down });
      if (t.history.length > HISTORY_DAYS) t.history = t.history.slice(-HISTORY_DAYS);
    }
    t.today = { date: day, up: 0, down: 0 };
  }
  if (ok) t.today.up += 1;
  else t.today.down += 1;

  const wasFailing = t.consecutiveFailures >= FAILURE_THRESHOLD;
  t.consecutiveFailures = ok ? 0 : t.consecutiveFailures + 1;
  const isFailing = t.consecutiveFailures >= FAILURE_THRESHOLD;

  t.lastStatus = ok ? "up" : "down";
  t.lastCheckedAt = new Date().toISOString();
  t.lastError = ok ? null : message;

  return { justFailed: !wasFailing && isFailing, justRecovered: wasFailing && ok };
}

function uptimePct(history, today) {
  const days = today ? [...history, { up: today.up, down: today.down }] : history;
  const totals = days.reduce((acc, d) => ({ up: acc.up + d.up, down: acc.down + d.down }), { up: 0, down: 0 });
  const total = totals.up + totals.down;
  return total === 0 ? 100 : (100 * totals.up) / total;
}

function renderBadge(targetState, id) {
  const pct = uptimePct(targetState.history, targetState.today);
  const color =
    targetState.consecutiveFailures >= FAILURE_THRESHOLD ? "red" : pct >= 99.5 ? "brightgreen" : pct >= 95 ? "yellow" : "orange";
  return {
    schemaVersion: 1,
    label: id,
    message: `${pct.toFixed(2)}% (90d)`,
    color,
  };
}

function renderStatusMd(state) {
  const lines = [
    "# Status",
    "",
    "Generated by `.github/workflows/uptime.yml` (every 5 minutes) — do not edit by hand.",
    "",
  ];
  for (const target of TARGETS) {
    const t = state.targets[target.id];
    if (!t) continue;
    const pct = uptimePct(t.history, t.today);
    lines.push(`## ${target.label}`);
    lines.push("");
    lines.push(`- Status: **${t.lastStatus === "up" ? "🟢 up" : "🔴 down"}** (last checked ${t.lastCheckedAt})`);
    lines.push(`- Uptime (last ${HISTORY_DAYS} days): **${pct.toFixed(2)}%**`);
    if (t.lastError) lines.push(`- Last error: \`${t.lastError}\``);
    lines.push("");
    lines.push("| Date | Up | Down |");
    lines.push("| --- | --- | --- |");
    const rows = [...t.history, t.today].filter(Boolean).slice(-HISTORY_DAYS);
    for (const row of rows.slice().reverse()) {
      lines.push(`| ${row.date} | ${row.up} | ${row.down} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

async function main() {
  const state = await loadState();
  const events = [];

  for (const target of TARGETS) {
    let ok = true;
    let message = null;
    try {
      await target.check();
    } catch (err) {
      ok = false;
      message = err instanceof Error ? err.message : String(err);
    }
    const { justFailed, justRecovered } = recordResult(state, target.id, ok, message);
    console.log(`[uptime] ${target.label}: ${ok ? "OK" : `FAIL — ${message}`}`);
    if (justFailed) events.push({ type: "failed", target });
    if (justRecovered) events.push({ type: "recovered", target });
  }

  await mkdir(dirname(statePath), { recursive: true });
  await writeFile(statePath, JSON.stringify(state, null, 2) + "\n");
  await writeFile(statusPath, renderStatusMd(state) + "\n");

  for (const target of TARGETS) {
    const badgePath = resolve(root, `docs/uptime-badge-${target.id}.json`);
    await writeFile(badgePath, JSON.stringify(renderBadge(state.targets[target.id], target.id), null, 2) + "\n");
  }

  if (events.length > 0) {
    console.log("EVENTS_JSON=" + JSON.stringify(events.map((e) => ({ type: e.type, target: e.target.id, label: e.target.label }))));
  }

  const anyDown = TARGETS.some((t) => state.targets[t.id]?.consecutiveFailures >= FAILURE_THRESHOLD);
  if (anyDown && process.env.UPTIME_STRICT_EXIT === "1") process.exitCode = 1;
}

main().catch((err) => {
  console.error("[uptime] fatal:", err);
  process.exitCode = 1;
});
